#!/bin/bash
set -euo pipefail

echo "--- :git: Waiting for ${BUILDKITE_REPO} @ ${BUILDKITE_COMMIT}"

until git ls-remote "${BUILDKITE_REPO}" | grep -q "${BUILDKITE_COMMIT}"; do
    sleep 10
done

echo "It's up ^.^"
